server:
  port: 8081

application:
  client:
    product:
      protocol: http
      host: localhost
      port: 8080
      basePath: /api/v2/products
      url: ${application.client.product.protocol}://${application.client.product.host}:${application.client.product.port}${application.client.product.basePath}